name: devshare

on:
  push:
    branches: -master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd packages/frontend && npm install
      - run: cd packages/frontend && npm run lint
